Added integration document for cloudanix
Cloudanix/librarium pull request #1
Opened 2022-09-05 06:49 UTC by ajinkya1986

Added Cloudanix integration Document

2022-09-05 08:00 UTC, taurusismysign requested changes
Pls make changes

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +metaDescription: 'Cloudanix container security helm chart for Spectro Cloud Palette'
Spectro CLoud are not two words? Please check

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix Container Security helm chart leverages Falco for to detect anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix Dashboard to view on which resource
for and to. grammar.

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix Container Security helm chart leverages Falco for to detect anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix Dashboard to view on which resource
@mpurusottamc Shall we mention Falco here?

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +This Helm chart helps to install multiple Cloudanix services for container protection. The following services are installed
This helm chart installs 3 Cloudanix services to enable container security capabilities. The services are listed below:

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +The chart installs the Falco community chart which is a dependency in Chart.yaml.
grammar?

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +The following Cloudanix Container Security Helm Chart versions are supported to work with Palette.
Grammar. 

Cloudanix helm chart supports the following versions with Palette.

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +The chart installs the Falco community chart which is a dependency in Chart.yaml.
Also, there are multiple references to Falco .. user might get confused. We could remove it.

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +The following Falco Charts Version is supported to work with Cloudanix Charts.
remove Falco reference.

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +| clusterName | Customer cluster name | NA | The name of the cluster on which the Cloudanix Container Securities Worloads should run. |
The name of the cluster on which Cloudanix container security capability will run.

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +- The minimum kubernetes version supported for falco is 1.15
remove "for falco"

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix Container Security helm chart leverages Falco for to detect anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix Dashboard to view on which resource
Cloudanix container security helm chart

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +- inventory-service
if we dont need it, pls remove.

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +| falco.ebpf.enabled | `true`, `false` | NA | If installed with ebpf probe enabled the value should be `true`. |
what's the default value?

2022-09-05 08:00 UTC, taurusismysign commented on content/docs/06-integrations/00-cloudanix.md
> +# Notable Parameters
@mpurusottamc I had a word with Ajinkya on this. My understanding is user dont have to provide any of these params and this is handled by SC for us. So, in that case we can remove it, right?

2022-09-05 08:01 UTC, ajinkya1986 commented on content/docs/06-integrations/00-cloudanix.md
> +metaDescription: 'Cloudanix container security helm chart for Spectro Cloud Palette'
Two words used in other docs as well

2022-09-05 08:34 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +metaDescription: 'Cloudanix container security helm chart for Spectro Cloud Palette'
I think, two words is okay. I see that in the docs page as well.

2022-09-05 08:34 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix Container Security helm chart leverages Falco for to detect anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix Dashboard to view on which resource
We should not.

2022-09-05 08:34 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +The chart installs the Falco community chart which is a dependency in Chart.yaml.
yes, let's remove any mention of falco.

2022-09-05 08:36 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +# Notable Parameters
Yeah. All of these values are pre-populated usign macros. I guess, we can remove them. Let me check another add-on for reference.

2022-09-06 05:17 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix container security helm chart detects anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix dashboard to view on which resources like pods, container
We should also highlight that our helm chart detects threats. something like, `detects threats and ano.....`

2022-09-06 05:18 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix container security helm chart detects anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix dashboard to view on which resources like pods, container
Spelling mistake, it should be `behaviors`.

2022-09-06 05:19 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +Cloudanix container security helm chart detects anamolous behaviours on kubernetes cluster and provides an interactive interface in Cloudanix dashboard to view on which resources like pods, container
after occuring, we should have a comma. Also, spelling mistake. `occurring, in real-time`

2022-09-06 05:19 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +* **0.0.3**
we should change version to 1.0.0

2022-09-06 05:20 UTC, mpurusottamc commented on content/docs/06-integrations/00-cloudanix.md
> +- The minimum kubernetes version supported is 1.15
kubernetes, K should be upper case.

2022-09-06 05:20 UTC, mpurusottamc requested changes
Please make the changes. Rest looks good.

2022-09-07 19:10 UTC, mpurusottamc approved these changes
looks good. Thanks for making the changes.

2022-09-07 19:10 UTC, merged